import React from 'react'
 const TokenContext = "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJKV1RfQ1VSUkVOVF9VU0VSIjoiQWRtaW4iLCJuYmYiOjE2MDA0MTAwNDMsImV4cCI6MTYwMDQyNDQ0MywiaWF0IjoxNjAwNDEwMDQzfQ.TpCDKtlv0qdKYnHGy-K9RDmfHa6NCgypC_S-owYWjC8"

 export default TokenContext
