import React from 'react'
 const TokenContext = "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJKV1RfQ1VSUkVOVF9VU0VSIjoiQWRtaW4iLCJuYmYiOjE1OTk5ODMwNjYsImV4cCI6MTU5OTk5NzQ2NiwiaWF0IjoxNTk5OTgzMDY2fQ.5B32wWNRvlDIKus4UszLQ-fHN3kDCvJAyuud7h-45Co"

 export default TokenContext
