import React from 'react'
 const TokenContext = "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJKV1RfQ1VSUkVOVF9VU0VSIjoiQWRtaW4iLCJuYmYiOjE1OTk5OTc5NjAsImV4cCI6MTYwMDAxMjM2MCwiaWF0IjoxNTk5OTk3OTYwfQ.agEIeQfOk67Ea4AlgkqAUFrBQCMzuU9jGvPrL0vK_DU"

 export default TokenContext
